ALTER TABLE tickets
    ALTER COLUMN subject DROP NOT NULL,
    ALTER COLUMN subject SET DEFAULT '';

ALTER TABLE tickets
    ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'UTC',
    ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at AT TIME ZONE 'UTC',
    ALTER COLUMN completed_at TYPE TIMESTAMP USING completed_at AT TIME ZONE 'UTC';

ALTER TABLE tickets
    ADD COLUMN IF NOT EXISTS closed_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS sender_email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS client VARCHAR(255),
    ADD COLUMN IF NOT EXISTS ticket_type VARCHAR(30),
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS due_date DATE,
    ADD COLUMN IF NOT EXISTS priority VARCHAR(30),
    ADD COLUMN IF NOT EXISTS thread_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS approval_token VARCHAR(255);
